services:
    postgres:
        image: postgres:17
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: root
            POSTGRES_DB: products-service
        ports:
            - "5439:5432"
        networks:
            - app-network
    postgres_testing:
        image: postgres:17
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: root
            POSTGRES_DB: products-service-testing
        networks:
            - app-network
    php-fpm:
        build:
            context: .
            dockerfile: docker/php-fpm/Dockerfile
        working_dir: /application
        volumes:
            - .:/application
        ports:
            - "9006:9000"
        networks:
            - app-network
        command: sh -c "composer install && php artisan migrate && php-fpm"
    nginx:
        image: nginx:alpine
        volumes:
            - '.:/application'
            - './docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - "6880:80"
        networks:
            - app-network
networks:
    app-network:
        driver: bridge
