version: "3.9"

services:
    postgres:
        container_name: product-service-postgres
        image: postgres:17
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: root
            POSTGRES_DB: products-service
        ports:
            - "5439:5432"
        networks:
            - app-network
    postgres_testing:
        container_name: product-service-postgres-testing
        image: postgres:17
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: root
            POSTGRES_DB: products-service-testing
        networks:
            - app-network
    php-fpm:
        container_name: product-service-php-fpm
        build:
            dockerfile: docker/php-fpm/Dockerfile
        working_dir: /application
        networks:
            - app-network
    nginx:
        container_name: product-service-nginx
        image: nginx:alpine
        volumes:
            - '.:/application'
            - './docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - "6880:80"
        networks:
            - app-network
        depends_on:
            - php-fpm
networks:
    app-network:
        driver: bridge
